dist: xenial
language: python
python:
- '3.7'
os:
- linux
script:
- pip3 install -r requirements-dev.txt
- pip3 install .
- python3 setup.py test
deploy:
  provider: pypi
  user: mrava87
  distributions: bdist_wheel
  skip_existing: true
  skip_upload_docs: true
  skip_cleanup: true
  on:
    tags: true
  password:
    secure: Er4noQo2sMKhtvtheKvvKKOfj8uNEhpjhBRf54y0S5e3HNK1U38nMZuKT7GXRwCDjPXzWRF6oZdlAyi1SRB0hPGtT4Ucm31k6qAEzi9Ph43T9BNIMIuIcEIwY3X2D9g5ySHyfEYLgGNAYzxttiKIhMPOk7vafUMsFUSh5ldZbY/ykSpcB8DiLKw+Z6+AV9pM5YTFn1Djn4pfC88G7tzFySw+b8BL9d8/hLAWmw70Kczh20l86zIOFV/CaW6ph9irssx9nrxz7W3Kb6YFl/QaOh34mEC0ZKoiz6LMdNAGX0RI0iCwtPHdUlPi2qSXXHLvLgqPXKjoqc2bTI19n39EBoSnIveyTYP1wUj3jRLG5pqeFr/Bo2Ti8By8Hye8Iqqdx2PT5wR8bWLiy+M1FMkeJjMT/ZvUudy00gg+7J/xRutBWhRmk2bZt6aCBG0NwpAVoN9UqssoXcYwFmRcOpleGNHo6Wi/0Rg59oAlN0PI+SCWMOcW1veKbsOgSi6nXisffgnZEsFWfEVZB0sLGMqFtBLAmY56PPKbEKqJXDZZ2MRcHDiZB0YfczewCeKdlPiRIQlpLDPu/xaUCiEAnvFZS1EKkpZ9F8/gpJey3e4UPUL+PPmAyMNA/4yBM5xrSjKVl09wuyzqvyTktBGDjaMHvZw0kwnysrmsdP5p30Rf3y8=
