dist: xenial
language: python
python:
- '3.7'
os:
- linux
script:
- pip3 install -r requirements-dev.txt
- pip3 install .
- python3 setup.py test
deploy:
  provider: pypi
  user: mrava87
  distributions: bdist_wheel
  skip_existing: true
  skip_upload_docs: true
  skip_cleanup: true
  on:
    tags: true
  password:
    secure: fy5rvzE1kGdtyME4Bym6rLsPsq4HaNGL/g0X3mNVQ0o1ly53gkj2V4fZIfhpor+Lr77LNgCmNXG0ObZy1QJ5XumMhCFhGT8tVQlelXBTkWYZNHe6IznpPyRQi90QNz27tcZCW78hKSwSQeIGfzaJ+8HB6CAu3K8t7BFuWssL5MIdqL5+kYfVRjVK0tFVyktDOj6kbi0MQTUsFWJwcZnDjYadT7VCHJv35aokENACZrtwjQdegiQ41HXfijE55VdisAT0aLipeZcQ5RKMaL7OybHb2B3hVAkCW0jhmFGW2iRyuMgvAiAEYFXwpkEZwPscpuxheSsCLeh4MkWFEjcRz+fhZHQ0kp5ukAu7lCfQLyoUMy5CmrFd29SvnbD/ijAqpAHO/vmdSgqVB8GE+OJcHRhvAwZXMHT8RSwxS2KgebIPRhhvckAoH0oZOPi4170HXS9AymY8NxqWXt+9jAYfVmB/7eV9zXE97ribSfLrMvs92FWEa8UzGWeuqsDbaUJQuwlsweaHR72gY2kLwYUH3PTVJxnKcx00YDG6xtenI6nyw9+rIqwTh0Br7MdRxX0QixZ1qyYeeHutj2Jndfk6n1PlykfKoMOcDjEA0SUwprH8uaUq8RH/IJvUI0PS/lsifwtBzMkD74GBZd4WiZa5FSHMxsO8P9qJLlqcY/pmvcY=
