# Azure pipeline for PyLops-gpu

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.6'
    architecture: 'x64'

- script: |
    python -m pip install --upgrade pip setuptools wheel django
    pip install -r requirements-dev.txt
    pip install pytest-azurepipelines pytest-cov
    pip install .
  displayName: 'Install dependencies and library'

- script: |
    python -m pytest pytests/
    pytest pytests/ --cov pylops_gpu --cov-report html
  condition: succeededOrFailed()
  displayName: 'Run tests'
