name: pylops-gpu
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python>=3.6.4
  - numpy>=1.15.0
  - scipy>=1.1.0
  - pytorch>=1.2.0
  - pylops
  - pip:
    - pytorch-complex-tensor